version: '3.1'

services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: order_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - om-network

  order-manager-api:
    image: order-manager-api:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    networks:
      - om-network
    depends_on:
      - postgresql
networks:
  om-network:
    driver: bridge
