version: '3.3'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: order_manager
      POSTGRES_USER: om_user
      POSTGRES_PASSWORD: om_user
    ports:
      - "5432:5432"
#    restart: unless-stopped
#    volumes:
#      - ./om-data:/var/lib/postgresql/data
#      - "$PWD/om-data:/var/lib/postgresql/data"
    networks:
      - om-network

  order-manager-api:
    image: order-manager-api:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    networks:
      - om-network
    depends_on:
      - postgresql

volumes:
  om-data:

networks:
  om-network:
    driver: bridge
