version: '3.1'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: order_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://localhost:5432/order_manager
    ports:
      - "5432:5432"
