server:
  servlet:
    context-path: /order-manager-api
spring:
  application:
    name: order-manager-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    enabled: true
    drop-first: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http:/localhost:8282/realms/OM_order-manager

#      client:
#        provider:
#          keycloak:
#            issuer-uri: http:/localhost:8282/realms/OM_order-manager
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: om-backend
#            authorization-grant-type: authorization_code
#            scope: openid

springdoc:
  swagger-ui:
    path: /swagger-ui.html