server:
  servlet:
    context-path: /order-manager
spring:
  application:
    name: order-manager
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    enabled: true
    drop-first: true

jwt:
  token:
    secret-key: ${JWT_TOKEN_SECRET_KEY:3B33F445EAB86CEF92C9CBA30B597D8F45DB5C252EDD30BDE90F9CF60E119D27}
    expired-access: ${JWT_TOKEN_EXPIRED_ACCESS:1440000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springframework.security: DEBUG