spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_manager
    username: om_user
    password: om_user
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
