spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_manager
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    enabled: true
    drop-first: true